<?php

namespace AppBundle\Repository;

/**
 * AssistanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssistanceRepository extends \Doctrine\ORM\EntityRepository
{
}
