<?php

namespace AppBundle\Repository;

/**
 * TemaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaryRepository extends \Doctrine\ORM\EntityRepository
{
}
